function fun_event_dates(DATES)

EVENT_DATES=[datenum('aug-10-2016');...
             datenum('mar-31-2017');...
             datenum('jun-06-2017');...
             datenum('aug-02-2017');...
             datenum('aug-11-2017');...
             datenum('aug-28-2017');...
             datenum('sep-28-2017');...
             datenum('oct-24-2017');...
             datenum('nov-11-2017');...
             datenum('feb-07-2018');...
             datenum('feb-22-2018');...
             ];

EVENT_DATES_txt=[{{'\fontsize{12}Bitfinex';'\fontsize{12}Haircut'          }};...
                 {{'\fontsize{12}Bitfinex';'\fontsize{10}($1.00 -> $1.25)'}};...
                 {{'\fontsize{12}Bitfinex';'\fontsize{10}($1.25 -> $2.00)'}};...
                 {{'\fontsize{12}Bitcoin' ;'\fontsize{12}Cash'             }};...
                 {{'\fontsize{12}Bitfinex';'\fontsize{10}($2.00 -> $2.50)'}};...
                 {{'\fontsize{12}Bitfinex';'\fontsize{10}($0.10)'          }};...
                 {{'\fontsize{12}Bitfinex';'\fontsize{10}($2.50 -> $3.50)'}};...
                 {{'\fontsize{12}Bitcoin' ;'\fontsize{12}Gold'             }};...
                 {{'\fontsize{12}Bitfinex';'\fontsize{10}($0.30)'          }};...
                 {{'\fontsize{12}Bitfinex';'\fontsize{10}($1.01)'          }};...
                 {{'\fontsize{12}ETHfinex';'\fontsize{12}NEC Token'        }};...
                 ];  
             
txt_loc=[34;...
         45;...
         85;...
         93;...
         105;...
         133;...
         118;...
         132;...
         145;...
         165;...
         185;...
           ];

J=size(EVENT_DATES,1);
YLIM=ylim;

for j=1:J
    if DATES(1)<=EVENT_DATES(j,1) && EVENT_DATES(j,1)<=DATES(end)
            line([EVENT_DATES(j,1) EVENT_DATES(j,1)],[txt_loc(j)+6,txt_loc(j)-7],'color','k','LineStyle','-','LineWidth',1.75);
            text( EVENT_DATES(j,1)+0.5,txt_loc(j),EVENT_DATES_txt{j},'color','k','FontWeight','bold');
    end
end
end